import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});



export const metadata: Metadata = {
  title: "Divakar's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html

      lang="en"
      className={`dark`}
      suppressHydrationWarning
    >
      <body>
                <ThemeProvider>
                    {children}
                </ThemeProvider>
            </body>
    </html>
  );
}
